import "@/styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/components/header.js";
import Footer from "@/components/footer.js";

import "@/public/assets/css/style.css";
import "@/public/assets/css/fontawesome.css";
import "@/public/assets/css/owl.css";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Component {...pageProps} />
      <Footer></Footer>
    </>
  );
}
